version: "1"

run:
  go: "1.23"
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
  disable:
    - lll
    - gocyclo
    - gocognit
    - typecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 